### ISSUE TITLE
Got stuck on last page of feedback

### ISSUE THREAD

**Issue by joegrimer** [altvalues/altvalues.github.io#3]
I assume this is because that part was simply unwritten, but I got stuck on the last page of feedback (about how active I was)

next question(null) ran, with no errors but didn't do anything. none of the buttons responded. I refreshed and went down the non feedback route to get me to the calculated results page (TBD).

I like the idea of an 8values like system which plays with the question and form, so I hope you carry on with this. I found 5 or so of the questions a bit confusing, but I reckon this project could be something.

**Comment by CIA-256** [comment]
@joegrimer Is it still an issue?
